### PR TITLE
Fix auto-update behavior

### PR DESCRIPTION
**Pull request by smarts**
- [x] Disable auto-update by default
- [x] Disable long-polling when auto-update is disabled

### CODE REVIEW

**Comment by andyalm** [comment]
I'm sorry for the churn on this, but it has occurred to me after spending a little time studying the code that we should have never tied auto updating being on or off to RetryDelay. RetryDelay is simply a setting to indicate how long it should wait to retry should it encounter an error response from Consul. I think I would feel more comfortable separating AutoUpdate and RetryDelay settings.

**Comment by andyalm** [comment]
What do you think about something like this:
```
public class AutoUpdateSettings
{
        public TimeSpan RetryDelay { get; set; } = Defaults.RetryDelay;
        public TimeSpan LongPollMaxWait { get; set; } = Defaults.LongPollMaxWait;
}
```
and then updating the `AutoUpdate` method to look something like this:
```
public ConsulConfigurationSource AutoUpdate(AutoUpdateSettings settings = null)
{
    _autoUpdateSettings = settings ?? new AutoUpdateSettings();
    return this;
}
```
Then pass `_autoUpdateSettings` to the `ConsulConfigurationProvider` to be consumed.

**Comment by smarts** [comment]
Is the `RetryDelay` on that class for error retries or auto-update interval? If it is for the latter then couldn't we use that for the long poll max interval instead of a separate setting? Long-polling seems like an implementation detail of auto-updating, and something that the user doesn't need to be concerned with at this level of abstraction.

**Comment by andyalm** [comment]
Retries only ever happen when AutoUpdate is enabled. It just throws if it gets errors on the first try because the app can't start in a good state. That is why I suggested grouping RetryDelay with AutoUpdate settings

**Comment by andyalm** [comment]
Ordinarily, I wouldn't expect someone to need to worry about overriding the defaults for either of these settings, though I think it's useful to at least allow it. The most common case is going to be calling AutoUpdate with no parameters though

**Comment by smarts** [comment]
Do you want to get rid of the `AutoUpdate(TimeSpan)` overload?

**Comment by andyalm** [comment]
Yes

**Comment by smarts** [comment]
I think `RetryDelay` is a bit ambiguous. What do you think about `ErrorRetryInterval` and `UpdateMaxInterval`? (still attempting to keep the implementation details out of the configuration library, especially since it depends on `IObservableConsul`, which may or may not use long-polling.)

**Comment by andyalm** [comment]
That works for me

**Comment by smarts** [comment]
@andyalm let me know if this latest change is more inline w/ what you think it should look like

**Pull request merged**
